### ISSUE TITLE
Few pre-launch issues 

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/jft-assistant#12]
- Searching for Hestia doesn't return the theme, probably sticky themes aren't searched for
- We show 880 reviews for Christmas Hestia which are probably nr of downloads, not rating

cc @selul

**Comment by selul** [comment]
@contactashish13 can you check please ?

**Comment by contactashish13** [comment]
@selul PRs: https://github.com/Codeinwp/justfreethemes/pull/74 and https://github.com/Codeinwp/jft-assistant/pull/13

**Comment by contactashish13** [comment]
@selul for number of reviews, I'm calculating the number of comments natively. Let me know if I should be using WPPR.

**Comment by selul** [comment]
@contactashish13 one more thing and we should be done: 
* after the user activates the plugin, we need to redirect him to that JFT browsing page. That should be done only once, after first install. 
* We should have also the sticky themes on the first page of the jft assistant. Basically when i go to the wp-admin page of JFT, we should see the first 6, those 6 themes that are sticky on the jft.com page.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/jft-assistant/pull/16
