### ISSUE TITLE
recommend orbitfox

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/jft-assistant#20]
@contactashish13 there is possible to hook into the theme installation process for themes installed through the assistant and when users click "install" on the dashboard demo page, show them a popup saying : " Do you wanna install the OrbitFox plugin as well for free uptime monitoring, sharing icons and google analytics integration?", if the user click yes, we install both the plugin and activate it + activate the theme.

We display that message only if orbitfox is not already installed, for inspiration on doing that check-out orbitfox template directory install.

cc @selul @rodica-andronache

**Comment by contactashish13** [comment]
@rodica-andronache PR: https://github.com/Codeinwp/jft-assistant/pull/21

**Comment by selul** [comment]
@contactashish13 it does not seems to work -> https://drive.google.com/file/d/1Y_JB5AsPKyszFPLQMYv2OtU0R9aGevWZ/view

Also, the popup should display only once per week, not every time when the user installs the theme.

**Comment by contactashish13** [comment]
@selul can't seem to watch the video

![image](https://user-images.githubusercontent.com/12953439/39520134-26681624-4e27-11e8-8087-393a69fb59e6.png)

**Comment by selul** [comment]
can you try now ?

**Comment by contactashish13** [comment]
@selul should be okay now. I've also added the 1 week interval.

**Comment by selul** [comment]
@contactashish13 looks solid now, well done.
